version: '3.8'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoDB
    ports:
      - "27017:27017"
    networks:
      - app-network
      
  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGO_DBNAME=mymongodb
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=mongoDB
      - MONGO_HOST=mongodb  # Use the service name as the hostname
      - MONGO_PORT=27017
      - MONGO_URL=mongodb://root:mongoDB@mongodb:27017/mymongodb?authSource=admin
    depends_on:
      - mongodb
    command: ["pytest"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
